// ─────────────────────────── Docs Search Index Plugin ─────────────────────────────

interface DocPageManifestEntry {
    path: string
    file: string // relative from package root
    section: string
    navGroup: string
    navLabel: string
    mdxSource?: string // relative path to .mdx source file, enables .md raw text serving
}

// Maps every static doc page route to its source file and nav metadata.
// Content strings are extracted automatically from the TSX source at build time.
export const DOC_PAGE_MANIFEST: DocPageManifestEntry[] = [
    // ── Général / Introduction ────────────────────────────────────────────────
    {
        path: "/documentation",
        file: "src/features/docs/general/RootGeneralDocPage.tsx",
        mdxSource: "features/docs/general/RootGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Accueil",
    },
    {
        path: "/documentation/fonctionnalités",
        file: "src/features/docs/general/features/FeaturesGeneralDocPage.tsx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Fonctionnalités",
        mdxSource: "features/docs/general/features/FeaturesGeneralDocPage.mdx",
    },
    {
        path: "/documentation/architecture",
        file: "src/features/docs/general/architecture/ArchitectureGeneralDocPage.tsx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Architecture",
        mdxSource: "features/docs/general/architecture/ArchitectureGeneralDocPage.mdx",
    },
    {
        path: "/documentation/philosophie",
        file: "src/features/docs/general/WhitepaperGeneralDocPage.tsx",
        mdxSource: "features/docs/general/WhitepaperGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Philosophie",
    },
    {
        path: "/documentation/support",
        file: "src/features/docs/general/SupportGeneralDocPage.tsx",
        mdxSource: "features/docs/general/SupportGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Support",
    },
    // ── Général / Légal ───────────────────────────────────────────────────────
    {
        path: "/documentation/mentions-légales",
        file: "src/features/docs/general/LegalGeneralDocPage.tsx",
        mdxSource: "features/docs/general/LegalGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Légal",
        navLabel: "Mentions légales",
    },
    {
        path: "/documentation/cgu",
        file: "src/features/docs/general/TermsGeneralDocPage.tsx",
        mdxSource: "features/docs/general/TermsGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Légal",
        navLabel: "Conditions Générales d'Utilisation",
    },
    {
        path: "/documentation/confidentialité",
        file: "src/features/docs/general/PrivacyGeneralDocPage.tsx",
        mdxSource: "features/docs/general/PrivacyGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Légal",
        navLabel: "Politique de confidentialité",
    },
    // ── Général / Nouveautés ──────────────────────────────────────────────────
    {
        path: "/documentation/mises-à-jour",
        file: "src/features/docs/general/UpdatesGeneralDocPage.tsx",
        mdxSource: "features/docs/general/UpdatesGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Nouveautés",
        navLabel: "Mises à jour",
    },
    // ── Comptabilité / Introduction ───────────────────────────────────────────
    {
        path: "/documentation/comptabilité",
        file: "src/features/docs/accounting/introduction/RootAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/RootAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Introduction",
        navLabel: "Accueil",
    },
    {
        path: "/documentation/comptabilité/introduction",
        file: "src/features/docs/accounting/introduction/IntroductionAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/IntroductionAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Introduction",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/comptabilité/introduction/partie-double",
        file: "src/features/docs/accounting/introduction/DoubleEntryAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/DoubleEntryAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Introduction",
        navLabel: "La partie double",
    },
    {
        path: "/documentation/comptabilité/introduction/écritures",
        file: "src/features/docs/accounting/introduction/EntriesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/EntriesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Introduction",
        navLabel: "Les écritures",
    },
    // ── Comptabilité / Comptes ────────────────────────────────────────────────
    {
        path: "/documentation/comptabilité/introduction/comptes",
        file: "src/features/docs/accounting/introduction/AccountsAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/AccountsAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Comptes",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/comptabilité/introduction/classes",
        file: "src/features/docs/accounting/introduction/ClassesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/ClassesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Comptes",
        navLabel: "Classes de comptes",
    },
    {
        path: "/documentation/comptabilité/ressources/comptes",
        file: "src/features/docs/accounting/resources/accounts/AccountsResourcesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/resources/accounts/AccountsResourcesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Comptes",
        navLabel: "Liste des comptes",
    },
    // ── Comptabilité / Documents ──────────────────────────────────────────────
    {
        path: "/documentation/comptabilité/documents",
        file: "src/features/docs/accounting/reports/ReportsAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/ReportsAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/comptabilité/documents/journal",
        file: "src/features/docs/accounting/reports/JournalAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/JournalAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Journal",
    },
    {
        path: "/documentation/comptabilité/documents/grand-livre",
        file: "src/features/docs/accounting/reports/LedgerAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/LedgerAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Grand livre",
    },
    {
        path: "/documentation/comptabilité/documents/balance",
        file: "src/features/docs/accounting/reports/BalanceAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/BalanceAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Balance",
    },
    {
        path: "/documentation/comptabilité/documents/bilan",
        file: "src/features/docs/accounting/reports/BalanceSheetAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/BalanceSheetAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Bilan",
    },
    {
        path: "/documentation/comptabilité/documents/compte-de-résultat",
        file: "src/features/docs/accounting/reports/IncomeStatementAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/IncomeStatementAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Compte de résultat",
    },
    {
        path: "/documentation/comptabilité/documents/annexe",
        file: "src/features/docs/accounting/reports/NotesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/NotesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Annexe",
    },
    {
        path: "/documentation/comptabilité/documents/fec",
        file: "src/features/docs/accounting/reports/FecAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/FecAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "FEC",
    },
    // ── Comptabilité / Scénarios ─────────────────────────────────────────────
    {
        path: "/documentation/comptabilité/ressources/scénarios",
        file: "src/features/docs/accounting/resources/scenarios/ScenariosResourcesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/resources/scenarios/ScenariosResourcesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Scénarios",
        navLabel: "Scénarios",
    },
    // ── Comptabilité / Glossaire ──────────────────────────────────────────────
    {
        path: "/documentation/comptabilité/ressources/glossaire",
        file: "src/features/docs/accounting/resources/glossary/GlossaryResourcesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/resources/glossary/GlossaryResourcesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Glossaire",
        navLabel: "Glossaire",
    },
    // ── Dashboard / Guide d'utilisation ──────────────────────────────────────
    {
        path: "/documentation/dashboard",
        file: "src/features/docs/dashboard/RootDashboardDocPage.tsx",
        mdxSource: "features/docs/dashboard/RootDashboardDocPage.mdx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Accueil",
    },
    {
        path: "/documentation/dashboard/démarrage",
        file: "src/features/docs/dashboard/GettingStartedDashboardDocPage.tsx",
        mdxSource: "features/docs/dashboard/GettingStartedDashboardDocPage.mdx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Démarrage",
    },
    {
        path: "/documentation/dashboard/organisations",
        file: "src/features/docs/dashboard/OrganizationsDashboardDocPage.tsx",
        mdxSource: "features/docs/dashboard/OrganizationsDashboardDocPage.mdx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Organisations",
    },
    {
        path: "/documentation/dashboard/exercices",
        file: "src/features/docs/dashboard/YearsDashboardDocPage.tsx",
        mdxSource: "features/docs/dashboard/YearsDashboardDocPage.mdx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Exercices",
    },
    {
        path: "/documentation/dashboard/écritures",
        file: "src/features/docs/dashboard/EntriesDashboardDocPage.tsx",
        mdxSource: "features/docs/dashboard/EntriesDashboardDocPage.mdx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Saisie des écritures",
    },
    {
        path: "/documentation/dashboard/stockage",
        file: "src/features/docs/dashboard/FilesDashboardDocPage.tsx",
        mdxSource: "features/docs/dashboard/FilesDashboardDocPage.mdx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Stockage",
    },
    {
        path: "/documentation/dashboard/documents",
        file: "src/features/docs/dashboard/ReportsDashboardDocPage.tsx",
        mdxSource: "features/docs/dashboard/ReportsDashboardDocPage.mdx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Documents comptables",
    },
    // ── Dashboard / Assistant IA ──────────────────────────────────────────────
    {
        path: "/documentation/dashboard/assistant",
        file: "src/features/docs/ai/RootAiDocPage.tsx",
        mdxSource: "features/docs/ai/RootAiDocPage.mdx",
        section: "Dashboard",
        navGroup: "Assistant IA",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/dashboard/assistant/modèles",
        file: "src/features/docs/ai/ModelsAiDocPage.tsx",
        mdxSource: "features/docs/ai/ModelsAiDocPage.mdx",
        section: "Dashboard",
        navGroup: "Assistant IA",
        navLabel: "Modèles",
    },
    {
        path: "/documentation/dashboard/assistant/outils",
        file: "src/features/docs/ai/ToolsAiDocPage.tsx",
        mdxSource: "features/docs/ai/ToolsAiDocPage.mdx",
        section: "Dashboard",
        navGroup: "Assistant IA",
        navLabel: "Outils",
    },
    {
        path: "/documentation/dashboard/assistant/ocr",
        file: "src/features/docs/ai/OcrAiDocPage.tsx",
        mdxSource: "features/docs/ai/OcrAiDocPage.mdx",
        section: "Dashboard",
        navGroup: "Assistant IA",
        navLabel: "OCR",
    },
    // ── CLI ────────────────────────────────────────────────────────────────────
    {
        path: "/documentation/cli",
        file: "src/features/docs/cli/RootCliDocPage.tsx",
        mdxSource: "features/docs/cli/RootCliDocPage.mdx",
        section: "CLI",
        navGroup: "CLI",
        navLabel: "Présentation",
    },
    {
        path: "/documentation/cli/installation",
        file: "src/features/docs/cli/InstallationCliDocPage.tsx",
        mdxSource: "features/docs/cli/InstallationCliDocPage.mdx",
        section: "CLI",
        navGroup: "CLI",
        navLabel: "Installation",
    },
    {
        path: "/documentation/cli/demarrer",
        file: "src/features/docs/cli/DemarrerCliDocPage.tsx",
        mdxSource: "features/docs/cli/DemarrerCliDocPage.mdx",
        section: "CLI",
        navGroup: "CLI",
        navLabel: "Démarrer",
    },
    {
        path: "/documentation/cli/authentification",
        file: "src/features/docs/cli/AuthenticationCliDocPage.tsx",
        mdxSource: "features/docs/cli/AuthenticationCliDocPage.mdx",
        section: "CLI",
        navGroup: "CLI",
        navLabel: "Authentification",
    },
    {
        path: "/documentation/cli/commandes",
        file: "src/features/docs/cli/CommandsCliDocPage.tsx",
        mdxSource: "features/docs/cli/CommandsCliDocPage.mdx",
        section: "CLI",
        navGroup: "Commandes",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/cli/commandes/organisation",
        file: "src/features/docs/cli/commands/OrgCommandsCliDocPage.tsx",
        mdxSource: "features/docs/cli/commands/OrgCommandsCliDocPage.mdx",
        section: "CLI",
        navGroup: "Commandes",
        navLabel: "Organisation",
    },
    {
        path: "/documentation/cli/commandes/membres",
        file: "src/features/docs/cli/commands/MembresCommandsCliDocPage.tsx",
        mdxSource: "features/docs/cli/commands/MembresCommandsCliDocPage.mdx",
        section: "CLI",
        navGroup: "Commandes",
        navLabel: "Membres",
    },
    {
        path: "/documentation/cli/commandes/cles-api",
        file: "src/features/docs/cli/commands/ClesApiCommandsCliDocPage.tsx",
        mdxSource: "features/docs/cli/commands/ClesApiCommandsCliDocPage.mdx",
        section: "CLI",
        navGroup: "Commandes",
        navLabel: "Clés API",
    },
    {
        path: "/documentation/cli/commandes/stockage",
        file: "src/features/docs/cli/commands/FichiersCommandsCliDocPage.tsx",
        mdxSource: "features/docs/cli/commands/FichiersCommandsCliDocPage.mdx",
        section: "CLI",
        navGroup: "Commandes",
        navLabel: "Stockage",
    },
    {
        path: "/documentation/cli/commandes/exercices",
        file: "src/features/docs/cli/commands/ExercicesCommandsCliDocPage.tsx",
        mdxSource: "features/docs/cli/commands/ExercicesCommandsCliDocPage.mdx",
        section: "CLI",
        navGroup: "Commandes",
        navLabel: "Exercices",
    },
    {
        path: "/documentation/cli/commandes/journaux",
        file: "src/features/docs/cli/commands/JournauxCommandsCliDocPage.tsx",
        mdxSource: "features/docs/cli/commands/JournauxCommandsCliDocPage.mdx",
        section: "CLI",
        navGroup: "Commandes",
        navLabel: "Journaux",
    },
    {
        path: "/documentation/cli/commandes/comptes",
        file: "src/features/docs/cli/commands/ComptesCommandsCliDocPage.tsx",
        mdxSource: "features/docs/cli/commands/ComptesCommandsCliDocPage.mdx",
        section: "CLI",
        navGroup: "Commandes",
        navLabel: "Comptes",
    },
    {
        path: "/documentation/cli/commandes/libelles",
        file: "src/features/docs/cli/commands/LibellesCommandsCliDocPage.tsx",
        mdxSource: "features/docs/cli/commands/LibellesCommandsCliDocPage.mdx",
        section: "CLI",
        navGroup: "Commandes",
        navLabel: "Libellés",
    },
    {
        path: "/documentation/cli/commandes/ecritures",
        file: "src/features/docs/cli/commands/EcrituresCommandsCliDocPage.tsx",
        mdxSource: "features/docs/cli/commands/EcrituresCommandsCliDocPage.mdx",
        section: "CLI",
        navGroup: "Commandes",
        navLabel: "Écritures",
    },
    {
        path: "/documentation/cli/commandes/exports",
        file: "src/features/docs/cli/commands/ExportsCommandsCliDocPage.tsx",
        mdxSource: "features/docs/cli/commands/ExportsCommandsCliDocPage.mdx",
        section: "CLI",
        navGroup: "Commandes",
        navLabel: "Exports",
    },
    {
        path: "/documentation/cli/commandes/bilans",
        file: "src/features/docs/cli/commands/BalanceSheetsCommandsCliDocPage.tsx",
        mdxSource: "features/docs/cli/commands/BalanceSheetsCommandsCliDocPage.mdx",
        section: "CLI",
        navGroup: "Commandes",
        navLabel: "Bilans",
    },
    {
        path: "/documentation/cli/commandes/comptes-de-resultat",
        file: "src/features/docs/cli/commands/IncomeStatementsCommandsCliDocPage.tsx",
        mdxSource: "features/docs/cli/commands/IncomeStatementsCommandsCliDocPage.mdx",
        section: "CLI",
        navGroup: "Commandes",
        navLabel: "Comptes de résultat",
    },

    // ── API ───────────────────────────────────────────────────────────────────
    {
        path: "/documentation/api",
        file: "src/features/docs/api/RootApiDocPage.tsx",
        mdxSource: "features/docs/api/RootApiDocPage.mdx",
        section: "API",
        navGroup: "API",
        navLabel: "Présentation",
    },
    {
        path: "/documentation/api/introduction",
        file: "src/features/docs/api/IntroductionApiDocPage.tsx",
        mdxSource: "features/docs/api/IntroductionApiDocPage.mdx",
        section: "API",
        navGroup: "API",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/api/authentification",
        file: "src/features/docs/api/AuthenticationApiDocPage.tsx",
        mdxSource: "features/docs/api/AuthenticationApiDocPage.mdx",
        section: "API",
        navGroup: "API",
        navLabel: "Authentification",
    },
    {
        path: "/documentation/api/organisation",
        file: "src/features/docs/api/OrganizationApiDocPage.tsx",
        mdxSource: "features/docs/api/OrganizationApiDocPage.mdx",
        section: "API",
        navGroup: "API",
        navLabel: "Organisation",
    },
    {
        path: "/documentation/api/exercice",
        file: "src/features/docs/api/YearApiDocPage.tsx",
        mdxSource: "features/docs/api/YearApiDocPage.mdx",
        section: "API",
        navGroup: "API",
        navLabel: "Exercice",
    },
    {
        path: "/documentation/api/stockage",
        file: "src/features/docs/api/FilesApiDocPage.tsx",
        mdxSource: "features/docs/api/FilesApiDocPage.mdx",
        section: "API",
        navGroup: "API",
        navLabel: "Fichiers et documents",
    },
]
