// ─────────────────────────── Docs Search Index Plugin ─────────────────────────────

interface DocPageManifestEntry {
    path: string
    file: string // relative from package root
    section: string
    navGroup: string
    navLabel: string
    mdxSource?: string // relative path to .mdx source file, enables .md raw text serving
}

// Maps every static doc page route to its source file and nav metadata.
// Content strings are extracted automatically from the TSX source at build time.
export const DOC_PAGE_MANIFEST: DocPageManifestEntry[] = [
    // ── Général / Introduction ────────────────────────────────────────────────
    {
        path: "/documentation",
        file: "features/docs/general/RootGeneralDocPage.tsx",
        mdxSource: "features/docs/general/RootGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Accueil",
    },
    {
        path: "/documentation/fonctionnalités",
        file: "src/features/docs/general/features/featuresGeneralDocPage.tsx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Fonctionnalités",
        mdxSource: "features/docs/general/features/FeaturesGeneralDocPage.mdx",
    },
    {
        path: "/documentation/architecture",
        file: "features/docs/general/architecture/ArchitectureGeneralDocPage.tsx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Architecture",
        mdxSource: "features/docs/general/architecture/ArchitectureGeneralDocPage.mdx",
    },
    {
        path: "/documentation/philosophie",
        file: "features/docs/general/WhitepaperGeneralDocPage.tsx",
        mdxSource: "features/docs/general/WhitepaperGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Philosophie",
    },
    {
        path: "/documentation/support",
        file: "features/docs/general/SupportGeneralDocPage.tsx",
        mdxSource: "features/docs/general/SupportGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Support",
    },
    // ── Général / Légal ───────────────────────────────────────────────────────
    {
        path: "/documentation/mentions-légales",
        file: "features/docs/general/LegalGeneralDocPage.tsx",
        mdxSource: "features/docs/general/LegalGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Légal",
        navLabel: "Mentions légales",
    },
    {
        path: "/documentation/cgu",
        file: "features/docs/general/TermsGeneralDocPage.tsx",
        mdxSource: "features/docs/general/TermsGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Légal",
        navLabel: "Conditions Générales d'Utilisation",
    },
    {
        path: "/documentation/confidentialité",
        file: "features/docs/general/PrivacyGeneralDocPage.tsx",
        mdxSource: "features/docs/general/PrivacyGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Légal",
        navLabel: "Politique de confidentialité",
    },
    // ── Comptabilité / Introduction ───────────────────────────────────────────
    {
        path: "/documentation/comptabilité",
        file: "features/docs/accounting/introduction/RootAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/RootAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Introduction",
        navLabel: "Accueil",
    },
    {
        path: "/documentation/comptabilité/introduction",
        file: "features/docs/accounting/introduction/IntroductionAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/IntroductionAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Introduction",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/comptabilité/introduction/partie-double",
        file: "features/docs/accounting/introduction/DoubleEntryAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/DoubleEntryAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Introduction",
        navLabel: "La partie double",
    },
    {
        path: "/documentation/comptabilité/introduction/écritures",
        file: "features/docs/accounting/introduction/EntriesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/EntriesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Introduction",
        navLabel: "Les écritures",
    },
    // ── Comptabilité / Comptes ────────────────────────────────────────────────
    {
        path: "/documentation/comptabilité/introduction/comptes",
        file: "features/docs/accounting/introduction/AccountsAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/AccountsAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Comptes",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/comptabilité/introduction/classes",
        file: "features/docs/accounting/introduction/ClassesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/ClassesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Comptes",
        navLabel: "Classes de comptes",
    },
    {
        path: "/documentation/comptabilité/ressources/comptes",
        file: "features/docs/accounting/resources/accounts/AccountsResourcesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/resources/accounts/AccountsResourcesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Comptes",
        navLabel: "Liste des comptes",
    },
    // ── Comptabilité / Documents ──────────────────────────────────────────────
    {
        path: "/documentation/comptabilité/documents",
        file: "features/docs/accounting/reports/ReportsAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/ReportsAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/comptabilité/documents/journal",
        file: "features/docs/accounting/reports/JournalAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/JournalAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Journal",
    },
    {
        path: "/documentation/comptabilité/documents/grand-livre",
        file: "features/docs/accounting/reports/LedgerAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/LedgerAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Grand livre",
    },
    {
        path: "/documentation/comptabilité/documents/balance",
        file: "features/docs/accounting/reports/BalanceAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/BalanceAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Balance",
    },
    {
        path: "/documentation/comptabilité/documents/bilan",
        file: "features/docs/accounting/reports/BalanceSheetAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/BalanceSheetAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Bilan",
    },
    {
        path: "/documentation/comptabilité/documents/compte-de-résultat",
        file: "features/docs/accounting/reports/IncomeStatementAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/IncomeStatementAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Compte de résultat",
    },
    {
        path: "/documentation/comptabilité/documents/annexe",
        file: "features/docs/accounting/reports/NotesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/NotesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Annexe",
    },
    {
        path: "/documentation/comptabilité/documents/fec",
        file: "features/docs/accounting/reports/FecAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/FecAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "FEC",
    },
    // ── Comptabilité / Scénarios ─────────────────────────────────────────────
    {
        path: "/documentation/comptabilité/ressources/scénarios",
        file: "features/docs/accounting/resources/scenarios/ScenariosResourcesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/resources/scenarios/ScenariosResourcesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Scénarios",
        navLabel: "Scénarios",
    },
    // ── Comptabilité / Glossaire ──────────────────────────────────────────────
    {
        path: "/documentation/comptabilité/ressources/glossaire",
        file: "features/docs/accounting/resources/glossary/GlossaryResourcesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/resources/glossary/GlossaryResourcesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Glossaire",
        navLabel: "Glossaire",
    },
    // ── Dashboard / Guide d'utilisation ──────────────────────────────────────
    {
        path: "/documentation/dashboard",
        file: "features/docs/dashboard/RootDashboardDocPage.tsx",
        mdxSource: "features/docs/dashboard/RootDashboardDocPage.mdx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Accueil",
    },
    {
        path: "/documentation/dashboard/démarrage",
        file: "features/docs/dashboard/GettingStartedDashboardDocPage.tsx",
        mdxSource: "features/docs/dashboard/GettingStartedDashboardDocPage.mdx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Démarrage",
    },
    {
        path: "/documentation/dashboard/organisations",
        file: "features/docs/dashboard/OrganizationsDashboardDocPage.tsx",
        mdxSource: "features/docs/dashboard/OrganizationsDashboardDocPage.mdx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Organisations",
    },
    {
        path: "/documentation/dashboard/exercices",
        file: "features/docs/dashboard/YearsDashboardDocPage.tsx",
        mdxSource: "features/docs/dashboard/YearsDashboardDocPage.mdx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Exercices",
    },
    {
        path: "/documentation/dashboard/écritures",
        file: "features/docs/dashboard/EntriesDashboardDocPage.tsx",
        mdxSource: "features/docs/dashboard/EntriesDashboardDocPage.mdx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Saisie des écritures",
    },
    {
        path: "/documentation/dashboard/stockage",
        file: "features/docs/dashboard/FilesDashboardDocPage.tsx",
        mdxSource: "features/docs/dashboard/FilesDashboardDocPage.mdx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Stockage",
    },
    {
        path: "/documentation/dashboard/documents",
        file: "features/docs/dashboard/ReportsDashboardDocPage.tsx",
        mdxSource: "features/docs/dashboard/ReportsDashboardDocPage.mdx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Documents comptables",
    },
    {
        path: "/documentation/dashboard/màj",
        file: "features/docs/dashboard/UpdatesDashboardDocPage.tsx",
        section: "Dashboard",
        navGroup: "Guide d'utilisation",
        navLabel: "Mises à jour",
        mdxSource: "features/docs/dashboard/UpdatesDashboardDocPage.mdx",
    },
    // ── Dashboard / Assistant IA ──────────────────────────────────────────────
    {
        path: "/documentation/dashboard/assistant",
        file: "features/docs/ai/RootAiDocPage.tsx",
        mdxSource: "features/docs/ai/RootAiDocPage.mdx",
        section: "Dashboard",
        navGroup: "Assistant IA",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/dashboard/assistant/modèles",
        file: "features/docs/ai/ModelsAiDocPage.tsx",
        mdxSource: "features/docs/ai/ModelsAiDocPage.mdx",
        section: "Dashboard",
        navGroup: "Assistant IA",
        navLabel: "Modèles",
    },
    {
        path: "/documentation/dashboard/assistant/outils",
        file: "features/docs/ai/ToolsAiDocPage.tsx",
        mdxSource: "features/docs/ai/ToolsAiDocPage.mdx",
        section: "Dashboard",
        navGroup: "Assistant IA",
        navLabel: "Outils",
    },
    {
        path: "/documentation/dashboard/assistant/ocr",
        file: "features/docs/ai/OcrAiDocPage.tsx",
        mdxSource: "features/docs/ai/OcrAiDocPage.mdx",
        section: "Dashboard",
        navGroup: "Assistant IA",
        navLabel: "OCR",
    },
    // ── API ───────────────────────────────────────────────────────────────────
    {
        path: "/documentation/api",
        file: "features/docs/api/RootApiDocPage.tsx",
        mdxSource: "features/docs/api/RootApiDocPage.mdx",
        section: "API",
        navGroup: "API",
        navLabel: "Présentation",
    },
    {
        path: "/documentation/api/introduction",
        file: "features/docs/api/IntroductionApiDocPage.tsx",
        mdxSource: "features/docs/api/IntroductionApiDocPage.mdx",
        section: "API",
        navGroup: "API",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/api/authentification",
        file: "features/docs/api/AuthenticationApiDocPage.tsx",
        mdxSource: "features/docs/api/AuthenticationApiDocPage.mdx",
        section: "API",
        navGroup: "API",
        navLabel: "Authentification",
    },
    {
        path: "/documentation/api/organisation",
        file: "features/docs/api/OrganizationApiDocPage.tsx",
        mdxSource: "features/docs/api/OrganizationApiDocPage.mdx",
        section: "API",
        navGroup: "API",
        navLabel: "Organisation",
    },
    {
        path: "/documentation/api/exercice",
        file: "features/docs/api/YearApiDocPage.tsx",
        mdxSource: "features/docs/api/YearApiDocPage.mdx",
        section: "API",
        navGroup: "API",
        navLabel: "Exercice",
    },
    {
        path: "/documentation/api/stockage",
        file: "features/docs/api/FilesApiDocPage.tsx",
        mdxSource: "features/docs/api/FilesApiDocPage.mdx",
        section: "API",
        navGroup: "API",
        navLabel: "Fichiers et documents",
    },
]
