// ─────────────────────────── Docs Search Index Plugin ─────────────────────────────

interface DocPageManifestEntry {
    path: string
    file: string // relative from package root
    section: string
    navGroup: string
    navLabel: string
    mdxSource?: string // relative path to .mdx source file, enables .md raw text serving
}

// Maps every static doc page route to its source file and nav metadata.
// Content strings are extracted automatically from the TSX source at build time.
export const DOC_PAGE_MANIFEST: DocPageManifestEntry[] = [
    // ── Général / Introduction ────────────────────────────────────────────────
    {
        path: "/documentation",
        file: "src/features/docs/general/RootGeneralDocPage.tsx",
        mdxSource: "features/docs/general/RootGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Accueil",
    },
    {
        path: "/documentation/fonctionnalités",
        file: "src/features/docs/general/features/FeaturesGeneralDocPage.tsx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Fonctionnalités",
        mdxSource: "features/docs/general/features/FeaturesGeneralDocPage.mdx",
    },
    {
        path: "/documentation/architecture",
        file: "src/features/docs/general/architecture/ArchitectureGeneralDocPage.tsx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Architecture",
        mdxSource: "features/docs/general/architecture/ArchitectureGeneralDocPage.mdx",
    },
    {
        path: "/documentation/philosophie",
        file: "src/features/docs/general/WhitepaperGeneralDocPage.tsx",
        mdxSource: "features/docs/general/WhitepaperGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Philosophie",
    },
    {
        path: "/documentation/support",
        file: "src/features/docs/general/SupportGeneralDocPage.tsx",
        mdxSource: "features/docs/general/SupportGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Introduction",
        navLabel: "Support",
    },
    // ── Général / Légal ───────────────────────────────────────────────────────
    {
        path: "/documentation/mentions-légales",
        file: "src/features/docs/general/LegalGeneralDocPage.tsx",
        mdxSource: "features/docs/general/LegalGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Légal",
        navLabel: "Mentions légales",
    },
    {
        path: "/documentation/cgu",
        file: "src/features/docs/general/TermsGeneralDocPage.tsx",
        mdxSource: "features/docs/general/TermsGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Légal",
        navLabel: "Conditions Générales d'Utilisation",
    },
    {
        path: "/documentation/confidentialité",
        file: "src/features/docs/general/PrivacyGeneralDocPage.tsx",
        mdxSource: "features/docs/general/PrivacyGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Légal",
        navLabel: "Politique de confidentialité",
    },
    // ── Général / Nouveautés ──────────────────────────────────────────────────
    {
        path: "/documentation/mises-à-jour",
        file: "src/features/docs/general/UpdatesGeneralDocPage.tsx",
        mdxSource: "features/docs/general/UpdatesGeneralDocPage.mdx",
        section: "Général",
        navGroup: "Nouveautés",
        navLabel: "Mises à jour",
    },
    // ── Guide / Prise en main ─────────────────────────────────────────────────
    {
        path: "/documentation/guide",
        file: "src/features/docs/guide/RootGuideDocPage.tsx",
        mdxSource: "features/docs/guide/RootGuideDocPage.mdx",
        section: "Guide",
        navGroup: "Accueil",
        navLabel: "Accueil",
    },
    {
        path: "/documentation/guide/démarrer",
        file: "src/features/docs/guide/PremiersPasGuideDocPage.tsx",
        mdxSource: "features/docs/guide/PremiersPasGuideDocPage.mdx",
        section: "Guide",
        navGroup: "Prise en main",
        navLabel: "Démarrer avec Arrhes",
    },
    {
        path: "/documentation/guide/installation",
        file: "src/features/docs/guide/InstallationGuideDocPage.tsx",
        mdxSource: "features/docs/guide/InstallationGuideDocPage.mdx",
        section: "Guide",
        navGroup: "Prise en main",
        navLabel: "Installation",
    },
    {
        path: "/documentation/guide/authentification",
        file: "src/features/docs/guide/AuthentificationGuideDocPage.tsx",
        mdxSource: "features/docs/guide/AuthentificationGuideDocPage.mdx",
        section: "Guide",
        navGroup: "Prise en main",
        navLabel: "Authentification",
    },
    // ── Guide / Organisation ──────────────────────────────────────────────────
    {
        path: "/documentation/guide/organisations",
        file: "src/features/docs/guide/OrganisationGuideDocPage.tsx",
        mdxSource: "features/docs/guide/OrganisationGuideDocPage.mdx",
        section: "Guide",
        navGroup: "Organisation",
        navLabel: "Organisations",
    },
    {
        path: "/documentation/guide/membres",
        file: "src/features/docs/guide/MembresGuideDocPage.tsx",
        mdxSource: "features/docs/guide/MembresGuideDocPage.mdx",
        section: "Guide",
        navGroup: "Organisation",
        navLabel: "Membres",
    },
    {
        path: "/documentation/guide/référence-api",
        file: "src/features/docs/guide/ReferenceApiGuideDocPage.tsx",
        mdxSource: "features/docs/guide/ReferenceApiGuideDocPage.mdx",
        section: "Guide",
        navGroup: "Référence",
        navLabel: "Référence API",
    },
    {
        path: "/documentation/guide/référence-cli",
        file: "src/features/docs/guide/ReferenceCliGuideDocPage.tsx",
        mdxSource: "features/docs/guide/ReferenceCliGuideDocPage.mdx",
        section: "Guide",
        navGroup: "Référence",
        navLabel: "Référence CLI",
    },
    // ── Guide / Exercice ──────────────────────────────────────────────────────
    {
        path: "/documentation/guide/exercices",
        file: "src/features/docs/guide/ExerciceGuideDocPage.tsx",
        mdxSource: "features/docs/guide/ExerciceGuideDocPage.mdx",
        section: "Guide",
        navGroup: "Exercice",
        navLabel: "Exercices",
    },
    {
        path: "/documentation/guide/comptes",
        file: "src/features/docs/guide/ComptesGuideDocPage.tsx",
        mdxSource: "features/docs/guide/ComptesGuideDocPage.mdx",
        section: "Guide",
        navGroup: "Exercice",
        navLabel: "Comptes",
    },
    {
        path: "/documentation/guide/journaux",
        file: "src/features/docs/guide/JournauxGuideDocPage.tsx",
        mdxSource: "features/docs/guide/JournauxGuideDocPage.mdx",
        section: "Guide",
        navGroup: "Exercice",
        navLabel: "Journaux",
    },
    {
        path: "/documentation/guide/libellés",
        file: "src/features/docs/guide/LibellesGuideDocPage.tsx",
        mdxSource: "features/docs/guide/LibellesGuideDocPage.mdx",
        section: "Guide",
        navGroup: "Exercice",
        navLabel: "Libellés",
    },
    // ── Guide / Écritures ─────────────────────────────────────────────────────
    {
        path: "/documentation/guide/écritures",
        file: "src/features/docs/guide/EcrituresGuideDocPage.tsx",
        section: "Guide",
        navGroup: "Écritures",
        navLabel: "Saisie des écritures",
    },
    // ── Guide / Documents ─────────────────────────────────────────────────────
    {
        path: "/documentation/guide/stockage",
        file: "src/features/docs/guide/StockageGuideDocPage.tsx",
        section: "Guide",
        navGroup: "Documents",
        navLabel: "Stockage & Fichiers",
    },
    {
        path: "/documentation/guide/documents",
        file: "src/features/docs/guide/DocumentsGuideDocPage.tsx",
        section: "Guide",
        navGroup: "Documents",
        navLabel: "Documents comptables",
    },
    {
        path: "/documentation/guide/bilans",
        file: "src/features/docs/guide/BilansGuideDocPage.tsx",
        section: "Guide",
        navGroup: "Documents",
        navLabel: "Bilans",
    },
    {
        path: "/documentation/guide/compte-de-résultat",
        file: "src/features/docs/guide/CompteDeResultatGuideDocPage.tsx",
        section: "Guide",
        navGroup: "Documents",
        navLabel: "Compte de résultat",
    },
    {
        path: "/documentation/guide/exports",
        file: "src/features/docs/guide/ExportsGuideDocPage.tsx",
        section: "Guide",
        navGroup: "Documents",
        navLabel: "Exports",
    },
    // ── Guide / Gestion ───────────────────────────────────────────────────────
    {
        path: "/documentation/guide/inventaire",
        file: "src/features/docs/guide/InventaireGuideDocPage.tsx",
        section: "Guide",
        navGroup: "Gestion",
        navLabel: "Inventaire",
    },
    // ── Guide / Assistant IA ──────────────────────────────────────────────────
    {
        path: "/documentation/guide/assistant",
        file: "src/features/docs/ai/RootAiDocPage.tsx",
        mdxSource: "features/docs/ai/RootAiDocPage.mdx",
        section: "Guide",
        navGroup: "Assistant IA",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/guide/assistant/modèles",
        file: "src/features/docs/ai/ModelsAiDocPage.tsx",
        mdxSource: "features/docs/ai/ModelsAiDocPage.mdx",
        section: "Guide",
        navGroup: "Assistant IA",
        navLabel: "Modèles",
    },
    {
        path: "/documentation/guide/assistant/outils",
        file: "src/features/docs/ai/ToolsAiDocPage.tsx",
        mdxSource: "features/docs/ai/ToolsAiDocPage.mdx",
        section: "Guide",
        navGroup: "Assistant IA",
        navLabel: "Outils",
    },
    {
        path: "/documentation/guide/assistant/ocr",
        file: "src/features/docs/ai/OcrAiDocPage.tsx",
        mdxSource: "features/docs/ai/OcrAiDocPage.mdx",
        section: "Guide",
        navGroup: "Assistant IA",
        navLabel: "OCR",
    },
    // ── Comptabilité / Introduction ───────────────────────────────────────────
    {
        path: "/documentation/comptabilité",
        file: "src/features/docs/accounting/introduction/RootAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/RootAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Introduction",
        navLabel: "Accueil",
    },
    {
        path: "/documentation/comptabilité/introduction",
        file: "src/features/docs/accounting/introduction/IntroductionAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/IntroductionAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Introduction",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/comptabilité/introduction/partie-double",
        file: "src/features/docs/accounting/introduction/DoubleEntryAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/DoubleEntryAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Introduction",
        navLabel: "La partie double",
    },
    {
        path: "/documentation/comptabilité/introduction/écritures",
        file: "src/features/docs/accounting/introduction/EntriesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/EntriesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Introduction",
        navLabel: "Les écritures",
    },
    // ── Comptabilité / Comptes ────────────────────────────────────────────────
    {
        path: "/documentation/comptabilité/introduction/comptes",
        file: "src/features/docs/accounting/introduction/AccountsAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/AccountsAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Comptes",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/comptabilité/introduction/classes",
        file: "src/features/docs/accounting/introduction/ClassesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/introduction/ClassesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Comptes",
        navLabel: "Classes de comptes",
    },
    {
        path: "/documentation/comptabilité/ressources/comptes",
        file: "src/features/docs/accounting/resources/accounts/AccountsResourcesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/resources/accounts/AccountsResourcesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Comptes",
        navLabel: "Liste des comptes",
    },
    // ── Comptabilité / Documents ──────────────────────────────────────────────
    {
        path: "/documentation/comptabilité/documents",
        file: "src/features/docs/accounting/reports/ReportsAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/ReportsAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Introduction",
    },
    {
        path: "/documentation/comptabilité/documents/journal",
        file: "src/features/docs/accounting/reports/JournalAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/JournalAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Journal",
    },
    {
        path: "/documentation/comptabilité/documents/grand-livre",
        file: "src/features/docs/accounting/reports/LedgerAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/LedgerAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Grand livre",
    },
    {
        path: "/documentation/comptabilité/documents/balance",
        file: "src/features/docs/accounting/reports/BalanceAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/BalanceAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Balance",
    },
    {
        path: "/documentation/comptabilité/documents/bilan",
        file: "src/features/docs/accounting/reports/BalanceSheetAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/BalanceSheetAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Bilan",
    },
    {
        path: "/documentation/comptabilité/documents/compte-de-résultat",
        file: "src/features/docs/accounting/reports/IncomeStatementAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/IncomeStatementAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Compte de résultat",
    },
    {
        path: "/documentation/comptabilité/documents/annexe",
        file: "src/features/docs/accounting/reports/NotesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/NotesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "Annexe",
    },
    {
        path: "/documentation/comptabilité/documents/fec",
        file: "src/features/docs/accounting/reports/FecAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/reports/FecAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Documents",
        navLabel: "FEC",
    },
    // ── Comptabilité / Scénarios ─────────────────────────────────────────────
    {
        path: "/documentation/comptabilité/ressources/scénarios",
        file: "src/features/docs/accounting/resources/scenarios/ScenariosResourcesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/resources/scenarios/ScenariosResourcesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Scénarios",
        navLabel: "Scénarios",
    },
    // ── Comptabilité / Glossaire ──────────────────────────────────────────────
    {
        path: "/documentation/comptabilité/ressources/glossaire",
        file: "src/features/docs/accounting/resources/glossary/GlossaryResourcesAccountingDocPage.tsx",
        mdxSource: "features/docs/accounting/resources/glossary/GlossaryResourcesAccountingDocPage.mdx",
        section: "Comptabilité",
        navGroup: "Glossaire",
        navLabel: "Glossaire",
    },
]
