/**
 * Batch migration script: updates all routeDefinition() calls in
 * packages/metadata/src/routes/dashboard/ to REST paths + correct HTTP methods.
 *
 * Run from the monorepo root:
 *   node scripts/migrate-routes.mjs
 */

import { readFileSync, writeFileSync } from "node:fs"

/** Map from OLD path template string to [NEW path, method] */
const PATH_MAP = new Map([
    // ── Public auth ────────────────────────────────────────────────────────
    [
        "`${routePath.public}/sign-in`",
        [
            "`${routePath.v1}/auth/sign-in`",
            "POST",
        ],
    ],
    [
        "`${routePath.public}/sign-up`",
        [
            "`${routePath.v1}/auth/sign-up`",
            "POST",
        ],
    ],
    [
        "`${routePath.public}/sign-out`",
        [
            "`${routePath.v1}/auth/sign-out`",
            "POST",
        ],
    ],
    [
        "`${routePath.public}/send-magic-link`",
        [
            "`${routePath.v1}/auth/magic-link`",
            "POST",
        ],
    ],
    [
        "`${routePath.public}/reset-password`",
        [
            "`${routePath.v1}/auth/reset-password`",
            "POST",
        ],
    ],
    [
        "`${routePath.public}/mollie-webhook`",
        [
            "`${routePath.v1}/webhooks/mollie`",
            "POST",
        ],
    ],

    // ── User (me) ───────────────────────────────────────────────────────────
    [
        "`${routePath.auth}/read-user-session`",
        [
            "`${routePath.v1}/users/me`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-user`",
        [
            "`${routePath.v1}/users/me`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/update-user-email`",
        [
            "`${routePath.v1}/users/me/email`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/update-user-password`",
        [
            "`${routePath.v1}/users/me/password`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/validate-user-email`",
        [
            "`${routePath.v1}/users/me/email/validate`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/resend-email-validation`",
        [
            "`${routePath.v1}/users/me/email/resend-validation`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/activate-user`",
        [
            "`${routePath.v1}/users/me/activate`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/delete-user`",
        [
            "`${routePath.v1}/users/me`",
            "DELETE",
        ],
    ],

    // ── Organizations ───────────────────────────────────────────────────────
    [
        "`${routePath.auth}/get-all-my-organization`",
        [
            "`${routePath.v1}/organizations`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/add-new-organization`",
        [
            "`${routePath.v1}/organizations`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/activate-organization-membership`",
        [
            "`${routePath.v1}/organizations/activate-membership`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-one-organization`",
        [
            "`${routePath.v1}/organizations/:idOrganization`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-organization`",
        [
            "`${routePath.v1}/organizations/:idOrganization`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-organization`",
        [
            "`${routePath.v1}/organizations/:idOrganization`",
            "DELETE",
        ],
    ],

    // Org users
    [
        "`${routePath.auth}/read-all-organization-users`",
        [
            "`${routePath.v1}/organizations/:idOrganization/users`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-organization-user`",
        [
            "`${routePath.v1}/organizations/:idOrganization/users`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-one-organization-user`",
        [
            "`${routePath.v1}/organizations/:idOrganization/users/:idOrganizationUser`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-organization-user`",
        [
            "`${routePath.v1}/organizations/:idOrganization/users/:idOrganizationUser`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-organization-user`",
        [
            "`${routePath.v1}/organizations/:idOrganization/users/:idOrganizationUser`",
            "DELETE",
        ],
    ],

    // API keys
    [
        "`${routePath.auth}/read-all-api-keys`",
        [
            "`${routePath.v1}/organizations/:idOrganization/api-keys`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-api-key`",
        [
            "`${routePath.v1}/organizations/:idOrganization/api-keys`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-api-key`",
        [
            "`${routePath.v1}/organizations/:idOrganization/api-keys/:idApiKey`",
            "DELETE",
        ],
    ],

    // Payments & billing
    [
        "`${routePath.auth}/read-all-organization-payments`",
        [
            "`${routePath.v1}/organizations/:idOrganization/payments`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/read-all-organization-billings`",
        [
            "`${routePath.v1}/organizations/:idOrganization/billings`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/read-organization-billing`",
        [
            "`${routePath.v1}/organizations/:idOrganization/billing`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/read-all-invoices`",
        [
            "`${routePath.v1}/organizations/:idOrganization/invoices`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/read-one-invoice`",
        [
            "`${routePath.v1}/organizations/:idOrganization/invoices/:idInvoice`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/generate-invoice-get-signed-url`",
        [
            "`${routePath.v1}/organizations/:idOrganization/invoices/:idInvoice/download-url`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/create-first-payment`",
        [
            "`${routePath.v1}/organizations/:idOrganization/billing/first-payment`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/create-payment-method-checkout`",
        [
            "`${routePath.v1}/organizations/:idOrganization/billing/payment-method-checkout`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/create-resource-subscription`",
        [
            "`${routePath.v1}/organizations/:idOrganization/billing/resource-subscription`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/create-wallet-top-up-checkout`",
        [
            "`${routePath.v1}/organizations/:idOrganization/billing/wallet-top-up`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/create-wallet-withdrawal`",
        [
            "`${routePath.v1}/organizations/:idOrganization/billing/wallet-withdrawal`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/update-tokens-subscription`",
        [
            "`${routePath.v1}/organizations/:idOrganization/billing/tokens-subscription`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/update-ocr-subscription`",
        [
            "`${routePath.v1}/organizations/:idOrganization/billing/ocr-subscription`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/update-storage-subscription`",
        [
            "`${routePath.v1}/organizations/:idOrganization/billing/storage-subscription`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/update-licence-subscription`",
        [
            "`${routePath.v1}/organizations/:idOrganization/billing/licence-subscription`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/cancel-subscription`",
        [
            "`${routePath.v1}/organizations/:idOrganization/billing/cancel-subscription`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/cancel-organization-billing`",
        [
            "`${routePath.v1}/organizations/:idOrganization/billing`",
            "DELETE",
        ],
    ],

    // ── Years ────────────────────────────────────────────────────────────────
    [
        "`${routePath.auth}/read-all-years`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-year`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-one-year`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-year`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-year`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear`",
            "DELETE",
        ],
    ],
    [
        "`${routePath.auth}/open-year`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/open`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/close-year`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/close`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/settle-balance-sheet`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/settle-balance-sheet`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/settle-income-statement`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/settle-income-statement`",
            "POST",
        ],
    ],

    // ── Accounts ──────────────────────────────────────────────────────────────
    [
        "`${routePath.auth}/read-all-accounts`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/accounts`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-account`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/accounts`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/generate-accounts`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/accounts/generate`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-one-account`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/accounts/:idAccount`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-account`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/accounts/:idAccount`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-account`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/accounts/:idAccount`",
            "DELETE",
        ],
    ],

    // ── Journals ──────────────────────────────────────────────────────────────
    [
        "`${routePath.auth}/read-all-journals`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/journals`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-journal`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/journals`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/generate-journals`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/journals/generate`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-one-journal`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/journals/:idJournal`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-journal`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/journals/:idJournal`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-journal`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/journals/:idJournal`",
            "DELETE",
        ],
    ],

    // ── Balance sheets ────────────────────────────────────────────────────────
    [
        "`${routePath.auth}/read-all-balance-sheets`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/balance-sheets`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-balance-sheet`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/balance-sheets`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/generate-balance-sheets`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/balance-sheets/generate`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/connect-accounts-to-balance-sheets`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/balance-sheets/connect-accounts`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-one-balance-sheet`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/balance-sheets/:idBalanceSheet`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-balance-sheet`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/balance-sheets/:idBalanceSheet`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-balance-sheet`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/balance-sheets/:idBalanceSheet`",
            "DELETE",
        ],
    ],

    // ── Income statements ─────────────────────────────────────────────────────
    [
        "`${routePath.auth}/read-all-income-statements`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/income-statements`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-income-statement`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/income-statements`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/generate-income-statements`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/income-statements/generate`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/connect-accounts-to-income-statements`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/income-statements/connect-accounts`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-one-income-statement`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/income-statements/:idIncomeStatement`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-income-statement`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/income-statements/:idIncomeStatement`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-income-statement`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/income-statements/:idIncomeStatement`",
            "DELETE",
        ],
    ],

    // ── Computations ──────────────────────────────────────────────────────────
    [
        "`${routePath.auth}/read-all-computations`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/computations`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-computation`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/computations`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/generate-computations`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/computations/generate`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-one-computation`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/computations/:idComputation`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-computation`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/computations/:idComputation`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-computation`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/computations/:idComputation`",
            "DELETE",
        ],
    ],

    // Computation income statements
    [
        "`${routePath.auth}/read-all-computation-income-statements`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/computations/:idComputation/income-statements`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-computation-income-statement`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/computations/:idComputation/income-statements`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-one-computation-income-statement`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/computations/:idComputation/income-statements/:idComputationIncomeStatement`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-computation-income-statement`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/computations/:idComputation/income-statements/:idComputationIncomeStatement`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-computation-income-statement`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/computations/:idComputation/income-statements/:idComputationIncomeStatement`",
            "DELETE",
        ],
    ],

    // ── Tags ──────────────────────────────────────────────────────────────────
    [
        "`${routePath.auth}/read-all-tags`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/tags`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-tag`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/tags`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-one-tag`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/tags/:idTag`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-tag`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/tags/:idTag`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-tag`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/tags/:idTag`",
            "DELETE",
        ],
    ],

    // ── Entries ───────────────────────────────────────────────────────────────
    [
        "`${routePath.auth}/read-all-entries`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-entry`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/create-one-entry-from-template`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/from-template`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-all-entry-tags`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entry-tags`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/read-one-entry`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/:idEntry`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-entry`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/:idEntry`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-entry`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/:idEntry`",
            "DELETE",
        ],
    ],
    [
        "`${routePath.auth}/reverse-one-entry`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/:idEntry/reverse`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/duplicate-one-entry`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/:idEntry/duplicate`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/compute-one-entry`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/:idEntry/compute`",
            "POST",
        ],
    ],

    // Entry lines
    [
        "`${routePath.auth}/read-all-entry-lines`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/:idEntry/lines`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-entry-line`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/:idEntry/lines`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/update-many-entry-lines`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/:idEntry/lines`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/read-one-entry-line`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/:idEntry/lines/:idEntryLine`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-entry-line`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/:idEntry/lines/:idEntryLine`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-entry-line`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/:idEntry/lines/:idEntryLine`",
            "DELETE",
        ],
    ],

    // Entry tags
    [
        "`${routePath.auth}/add-one-entry-tag`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/:idEntry/tags`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/remove-one-entry-tag`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/entries/:idEntry/tags/:idTag`",
            "DELETE",
        ],
    ],

    // ── Files ─────────────────────────────────────────────────────────────────
    [
        "`${routePath.auth}/read-all-files`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/files`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-file`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/files`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-one-file`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/files/:idFile`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-file`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/files/:idFile`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-file`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/files/:idFile`",
            "DELETE",
        ],
    ],
    [
        "`${routePath.auth}/ocr-file`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/files/:idFile/ocr`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/generate-file-put-signed-url`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/files/:idFile/upload-url`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/generate-file-get-signed-url`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/files/:idFile/download-url`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/generate-file-delete-signed-url`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/files/:idFile/delete-url`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/finalize-file-upload`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/files/:idFile/finalize`",
            "POST",
        ],
    ],

    // ── Folders ───────────────────────────────────────────────────────────────
    [
        "`${routePath.auth}/read-all-folders`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/folders`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-folder`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/folders`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-one-folder`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/folders/:idFolder`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-folder`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/folders/:idFolder`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-folder`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/folders/:idFolder`",
            "DELETE",
        ],
    ],

    // ── Reports ───────────────────────────────────────────────────────────────
    [
        "`${routePath.auth}/generate-income-statement-xml`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/reports/income-statement`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/generate-balance-sheet-xml`",
        [
            "`${routePath.v1}/organizations/:idOrganization/years/:idYear/reports/balance-sheet`",
            "POST",
        ],
    ],

    // ── Agent ─────────────────────────────────────────────────────────────────
    [
        "`${routePath.auth}/read-all-agent-sessions`",
        [
            "`${routePath.v1}/agent/sessions`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-agent-session`",
        [
            "`${routePath.v1}/agent/sessions`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-one-agent-session`",
        [
            "`${routePath.v1}/agent/sessions/:idAgentSession`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-agent-session`",
        [
            "`${routePath.v1}/agent/sessions/:idAgentSession`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/delete-one-agent-session`",
        [
            "`${routePath.v1}/agent/sessions/:idAgentSession`",
            "DELETE",
        ],
    ],
    [
        "`${routePath.auth}/read-all-agent-messages`",
        [
            "`${routePath.v1}/agent/sessions/:idAgentSession/messages`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-agent-message`",
        [
            "`${routePath.v1}/agent/sessions/:idAgentSession/messages`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/get-stream-for-agent-message`",
        [
            "`${routePath.v1}/agent/sessions/:idAgentSession/messages/:idAgentMessage/stream`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/get-chat-stream`",
        [
            "`${routePath.v1}/agent/sessions/:idAgentSession/stream`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/undo-agent-action`",
        [
            "`${routePath.v1}/agent/sessions/:idAgentSession/undo`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/create-one-agent-file`",
        [
            "`${routePath.v1}/agent/sessions/:idAgentSession/files`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/search-referenceable`",
        [
            "`${routePath.v1}/agent/search`",
            "GET",
        ],
    ],

    // ── Support / tickets ─────────────────────────────────────────────────────
    [
        "`${routePath.auth}/read-all-tickets`",
        [
            "`${routePath.v1}/support/tickets`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-ticket`",
        [
            "`${routePath.v1}/support/tickets`",
            "POST",
        ],
    ],
    [
        "`${routePath.auth}/read-one-ticket`",
        [
            "`${routePath.v1}/support/tickets/:idTicket`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/update-one-ticket`",
        [
            "`${routePath.v1}/support/tickets/:idTicket`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/update-one-ticket-status`",
        [
            "`${routePath.v1}/support/tickets/:idTicket/status`",
            "PATCH",
        ],
    ],
    [
        "`${routePath.auth}/read-all-ticket-messages`",
        [
            "`${routePath.v1}/support/tickets/:idTicket/messages`",
            "GET",
        ],
    ],
    [
        "`${routePath.auth}/create-one-ticket-message`",
        [
            "`${routePath.v1}/support/tickets/:idTicket/messages`",
            "POST",
        ],
    ],
])

import { glob } from "node:fs/promises"
import { join } from "node:path"

const ROOT = new URL("../packages/metadata/src/routes/dashboard", import.meta.url).pathname

let filesUpdated = 0
let filesSkipped = 0

for await (const entry of glob("**/*.ts", {
    cwd: ROOT,
})) {
    const filePath = join(ROOT, entry)
    const original = readFileSync(filePath, "utf8")
    let updated = original

    for (const [oldPath, [newPath, method]] of PATH_MAP.entries()) {
        if (!updated.includes(oldPath)) continue

        // Replace path value
        updated = updated.replace(oldPath, newPath)

        // Inject method field after `protocol:` line if not already present
        if (!updated.includes("method:")) {
            updated = updated.replace(/(\s+protocol:\s*"(?:http|ws)",)/, `$1\n    method: "${method}",`)
        }

        break // each file has one routeDefinition
    }

    if (updated !== original) {
        writeFileSync(filePath, updated, "utf8")
        filesUpdated++
        console.log(`✓ ${entry}`)
    } else {
        filesSkipped++
    }
}

console.log(`\nDone. Updated: ${filesUpdated}, Skipped: ${filesSkipped}`)
