import type { sqlClient } from "#src/clients/sqlClient.js"
import {
    addOneEntryTag,
    closeYearData,
    computeOneEntry,
    createOneAccount,
    createOneBalanceSheet,
    createOneComputation,
    createOneComputationIncomeStatement,
    createOneEntry,
    createOneEntryFromTemplate,
    createOneEntryLine,
    createOneFile,
    createOneFolder,
    createOneIncomeStatement,
    createOneJournal,
    createOneTag,
    createOneYearData,
    deleteOneAccount,
    deleteOneBalanceSheet,
    deleteOneComputation,
    deleteOneComputationIncomeStatement,
    deleteOneEntry,
    deleteOneEntryLine,
    deleteOneFile,
    deleteOneFolder,
    deleteOneIncomeStatement,
    deleteOneJournal,
    deleteOneTag,
    duplicateOneEntry,
    generateBalanceSheetXml,
    generateIncomeStatementXml,
    openYearData,
    readAllAccounts,
    readAllBalanceSheets,
    readAllComputationIncomeStatements,
    readAllComputations,
    readAllEntries,
    readAllEntryLines,
    readAllEntryTags,
    readAllFiles,
    readAllFolders,
    readAllIncomeStatements,
    readAllJournals,
    readAllTags,
    readAllYearsData,
    readOneAccount,
    readOneBalanceSheet,
    readOneComputation,
    readOneComputationIncomeStatement,
    readOneEntry,
    readOneEntryLine,
    readOneFile,
    readOneFolder,
    readOneIncomeStatement,
    readOneJournal,
    readOneTag,
    readOneYearData,
    removeOneEntryTag,
    settleBalanceSheet,
    settleIncomeStatement,
    updateManyEntryLines,
    updateOneAccount,
    updateOneBalanceSheet,
    updateOneComputation,
    updateOneComputationIncomeStatement,
    updateOneEntry,
    updateOneEntryLine,
    updateOneFile,
    updateOneFolder,
    updateOneIncomeStatement,
    updateOneJournal,
    updateOneTag,
    updateOneYearData,
} from "./crudOperations.js"

type DB = ReturnType<typeof sqlClient>

type RouteHandler = (db: DB, idOrganization: string, body: Record<string, unknown>) => Promise<unknown>

const routeHandlers: Record<string, RouteHandler> = {
    "read-all-years": (db, org) => readAllYearsData(db, org),
    "create-one-year": (db, org, body) => createOneYearData(db, org, body),
    "read-one-year": (db, org, body) => readOneYearData(db, org, body),
    "update-one-year": (db, org, body) => updateOneYearData(db, org, body),
    "close-year": (db, org, body) => closeYearData(db, org, body),
    "open-year": (db, org, body) => openYearData(db, org, body),
    "settle-balance-sheet": (db, org, body) => settleBalanceSheet(db, org, body),
    "settle-income-statement": (db, org, body) => settleIncomeStatement(db, org, body),
    "create-one-entry": (db, org, body) => createOneEntry(db, org, body),
    "create-one-entry-from-template": (db, org, body) => createOneEntryFromTemplate(db, org, body),
    "read-all-entries": (db, org, body) => readAllEntries(db, org, body),
    "read-one-entry": (db, org, body) => readOneEntry(db, org, body),
    "update-one-entry": (db, org, body) => updateOneEntry(db, org, body),
    "delete-one-entry": (db, org, body) => deleteOneEntry(db, org, body),
    "duplicate-one-entry": (db, org, body) => duplicateOneEntry(db, org, body),
    "compute-one-entry": (db, org, body) => computeOneEntry(db, org, body),
    "create-one-entry-line": (db, org, body) => createOneEntryLine(db, org, body),
    "read-all-entry-lines": (db, org, body) => readAllEntryLines(db, org, body),
    "read-one-entry-line": (db, org, body) => readOneEntryLine(db, org, body),
    "update-one-entry-line": (db, org, body) => updateOneEntryLine(db, org, body),
    "update-many-entry-lines": (db, org, body) => updateManyEntryLines(db, org, body),
    "delete-one-entry-line": (db, org, body) => deleteOneEntryLine(db, org, body),
    "read-all-entry-tags": (db, org, body) => readAllEntryTags(db, org, body),
    "add-one-entry-tag": (db, org, body) => addOneEntryTag(db, org, body),
    "remove-one-entry-tag": (db, org, body) => removeOneEntryTag(db, org, body),
    "create-one-account": (db, org, body) => createOneAccount(db, org, body),
    "read-all-accounts": (db, org, body) => readAllAccounts(db, org, body),
    "read-one-account": (db, org, body) => readOneAccount(db, org, body),
    "update-one-account": (db, org, body) => updateOneAccount(db, org, body),
    "delete-one-account": (db, org, body) => deleteOneAccount(db, org, body),
    "create-one-journal": (db, org, body) => createOneJournal(db, org, body),
    "read-all-journals": (db, org, body) => readAllJournals(db, org, body),
    "read-one-journal": (db, org, body) => readOneJournal(db, org, body),
    "update-one-journal": (db, org, body) => updateOneJournal(db, org, body),
    "delete-one-journal": (db, org, body) => deleteOneJournal(db, org, body),
    "create-one-tag": (db, org, body) => createOneTag(db, org, body),
    "read-all-tags": (db, org) => readAllTags(db, org),
    "read-one-tag": (db, org, body) => readOneTag(db, org, body),
    "update-one-tag": (db, org, body) => updateOneTag(db, org, body),
    "delete-one-tag": (db, org, body) => deleteOneTag(db, org, body),
    "create-one-balance-sheet": (db, org, body) => createOneBalanceSheet(db, org, body),
    "read-all-balance-sheets": (db, org, body) => readAllBalanceSheets(db, org, body),
    "read-one-balance-sheet": (db, org, body) => readOneBalanceSheet(db, org, body),
    "update-one-balance-sheet": (db, org, body) => updateOneBalanceSheet(db, org, body),
    "delete-one-balance-sheet": (db, org, body) => deleteOneBalanceSheet(db, org, body),
    "create-one-income-statement": (db, org, body) => createOneIncomeStatement(db, org, body),
    "read-all-income-statements": (db, org, body) => readAllIncomeStatements(db, org, body),
    "read-one-income-statement": (db, org, body) => readOneIncomeStatement(db, org, body),
    "update-one-income-statement": (db, org, body) => updateOneIncomeStatement(db, org, body),
    "delete-one-income-statement": (db, org, body) => deleteOneIncomeStatement(db, org, body),
    "create-one-computation": (db, org, body) => createOneComputation(db, org, body),
    "read-all-computations": (db, org, body) => readAllComputations(db, org, body),
    "read-one-computation": (db, org, body) => readOneComputation(db, org, body),
    "update-one-computation": (db, org, body) => updateOneComputation(db, org, body),
    "delete-one-computation": (db, org, body) => deleteOneComputation(db, org, body),
    "create-one-computation-income-statement": (db, org, body) => createOneComputationIncomeStatement(db, org, body),
    "read-all-computation-income-statements": (db, org, body) => readAllComputationIncomeStatements(db, org, body),
    "read-one-computation-income-statement": (db, org, body) => readOneComputationIncomeStatement(db, org, body),
    "update-one-computation-income-statement": (db, org, body) => updateOneComputationIncomeStatement(db, org, body),
    "delete-one-computation-income-statement": (db, org, body) => deleteOneComputationIncomeStatement(db, org, body),
    "create-one-file": (db, org, body) => createOneFile(db, org, body),
    "read-all-files": (db, org, body) => readAllFiles(db, org, body),
    "read-one-file": (db, org, body) => readOneFile(db, org, body),
    "update-one-file": (db, org, body) => updateOneFile(db, org, body),
    "delete-one-file": (db, org, body) => deleteOneFile(db, org, body),
    "create-one-folder": (db, org, body) => createOneFolder(db, org, body),
    "read-all-folders": (db, org) => readAllFolders(db, org),
    "read-one-folder": (db, org, body) => readOneFolder(db, org, body),
    "update-one-folder": (db, org, body) => updateOneFolder(db, org, body),
    "delete-one-folder": (db, org, body) => deleteOneFolder(db, org, body),
    "read-all-documents": (_db, _org) => Promise.resolve({ error: "Document listing is no longer available" }),
    "read-one-document": (_db, _org) => Promise.resolve({ error: "Document read is no longer available" }),
    "generate-balance-sheet-xml": (db, org, body) => generateBalanceSheetXml(db, org, body),
    "generate-income-statement-xml": (db, org, body) => generateIncomeStatementXml(db, org, body),
}

export async function executeWorkerRoute(
    db: DB,
    idOrganization: string,
    pathSuffix: string,
    body: Record<string, unknown>,
): Promise<unknown> {
    const handler = routeHandlers[pathSuffix]
    if (!handler) {
        return { error: `Unknown route: ${pathSuffix}` }
    }
    try {
        return await handler(db, idOrganization, body)
    } catch (error: unknown) {
        const msg = error instanceof Error ? error.message : String(error)
        return { error: true, message: `Erreur lors de l'exécution de ${pathSuffix}: ${msg}` }
    }
}
