name: Release CLI

on:
  release:
    types: [published]

jobs:
  upload-assets:
    name: Upload CLI scripts
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Upload release assets
        run: .scripts/release-cli.sh "${{ github.event.release.tag_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
